# Generated by Django 4.2.7 on 2023-11-20 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{9,10}$')])),
                ('email', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other')], max_length=10)),
                ('profile_photo', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{9,10}$')])),
                ('email', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-Binary'), ('OTHER', 'Other')], max_length=10)),
                ('profile_photo', models.ImageField(upload_to='uploads/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('available', models.BooleanField(default=True)),
                ('remote', models.BooleanField(default=True)),
                ('in_person', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
