# Generated by Django 4.2.7 on 2023-11-21 00:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9]|[a-zA-Z]]')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9]|[a-zA-Z]]')]),
        ),
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATHEMATICS', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGLISH', 'English')], max_length=20)),
                ('level', models.CharField(choices=[('NCEA_1', 'NCEA 1'), ('NCEA_2', 'NCEA 2'), ('NCEA_3', 'NCEA 3'), ('NCEA_SCHOLARSHIP', 'NCEA Scholarship'), ('100_LEVEL', '100 Level'), ('200_LEVEL', '200 Level'), ('300_LEVEL', '300 Level'), ('400_LEVEL', '400 Level'), ('POSTGRADUATE', 'Postgraduate')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor4u.student')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATHEMATICS', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGLISH', 'English')], max_length=20)),
                ('level', models.CharField(choices=[('NCEA_1', 'NCEA 1'), ('NCEA_2', 'NCEA 2'), ('NCEA_3', 'NCEA 3'), ('NCEA_SCHOLARSHIP', 'NCEA Scholarship'), ('100_LEVEL', '100 Level'), ('200_LEVEL', '200 Level'), ('300_LEVEL', '300 Level'), ('400_LEVEL', '400 Level'), ('POSTGRADUATE', 'Postgraduate')], max_length=20)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor4u.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATHEMATICS', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGLISH', 'English')], max_length=20)),
                ('level', models.CharField(choices=[('NCEA_1', 'NCEA 1'), ('NCEA_2', 'NCEA 2'), ('NCEA_3', 'NCEA 3'), ('NCEA_SCHOLARSHIP', 'NCEA Scholarship'), ('100_LEVEL', '100 Level'), ('200_LEVEL', '200 Level'), ('300_LEVEL', '300 Level'), ('400_LEVEL', '400 Level'), ('POSTGRADUATE', 'Postgraduate')], max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2023, 11, 21, 0, 38, 30, 224222, tzinfo=datetime.timezone.utc))),
                ('duration', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor4u.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor4u.tutor')),
            ],
        ),
    ]
