# Generated by Django 5.0 on 2024-01-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='tutor',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED_AVAILABILITY', 'Limited-Availability'), ('NOT_AVAILABLE', 'Not Available')], default='', max_length=20),
        ),
    ]
