# Generated by Django 4.2.7 on 2023-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0002_alter_student_first_name_alter_tutor_first_name_want_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(),
        ),
    ]
