# Generated by Django 4.2.7 on 2023-11-21 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0003_alter_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=64, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z][[a-zA-Z][\\s-]]+')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z][[a-zA-Z][\\s-]]+')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9][a-zA-Z]]')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(max_length=64, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z][[a-zA-Z][\\s-]]+')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z][[a-zA-Z][\\s-]]+')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9][a-zA-Z]]')]),
        ),
    ]
