# Generated by Django 4.2.7 on 2023-11-21 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0004_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9]|[a-zA-Z]]')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[[0-9]|[a-zA-Z]]')]),
        ),
    ]
