# Generated by Django 4.2.7 on 2023-11-21 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0005_alter_student_password_alter_tutor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator()]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator()]),
        ),
    ]
