# Generated by Django 4.2.7 on 2023-11-21 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor4u', '0007_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
