import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepagemvp">HomePageMVP</Link>
        </li>
        <li>
          <Link to="/findatutorpagemvp">FindATutorPageMVP</Link>
        </li>
        <li>
          <Link to="/tutorprofilepagemvp">TutorProfilePageMVP</Link>
        </li>
        <li>
          <Link to="/contactusmvp">ContactUsMVP</Link>
        </li>
        <li>
          <Link to="/infodivmvp">InfoDivMVP</Link>
        </li>
        <li>
          <Link to="/tutorcodeofconductmvp">TutorCodeofConductMVP</Link>
        </li>
        <li>
          <Link to="/loginpagemvp">LoginPageMVP</Link>
        </li>
        <li>
          <Link to="/tutoronboardingmvp">TutorOnboardingMVP</Link>
        </li>
        <li>
          <Link to="/tutordashboardmvp">TutorDashboardMVP</Link>
        </li>
        <li>
          <Link to="/desktopframecontainermvp">DesktopFrameContainerMVP</Link>
        </li>
        <li>
          <Link to="/findatutorpagemvpone">FindATutorPageMVPOne</Link>
        </li>
        <li>
          <Link to="/tutorprofilepagedesktopmvp">
            TutorProfilePageDesktopMVP
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
