import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/findatutor">FindATutor</Link>
        </li>
        <li>
          <Link to="/tutorprofile">TutorProfile</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/modals">Modals</Link>
        </li>
        <li>
          <Link to="/tutorcodeofconduct">TutorCodeofConduct</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/tutoronboarding">TutorOnboarding</Link>
        </li>
        <li>
          <Link to="/tutordashboard">TutorDashboard</Link>
        </li>
        <li>
          <Link to="/infodiv">InfoDiv</Link>
        </li>
        <li>
          <Link to="/tutorprofileloggedin">TutorProfileLoggedIn</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
