import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">TutorJobBoard</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/findatutor">FindATutor</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/tutorprofilepagedesktop">TutorProfilePageDesktop</Link>
        </li>
        <li>
          <Link to="/admindashboard">AdminDashboard</Link>
        </li>
        <li>
          <Link to="/admintutors">AdminTutors</Link>
        </li>
        <li>
          <Link to="/adminlessons">AdminLessons</Link>
        </li>
        <li>
          <Link to="/tabdivlogincreated">TabDivLoginCreated</Link>
        </li>
        <li>
          <Link to="/tabdivlessonrequests">TabDivLessonRequests</Link>
        </li>
        <li>
          <Link to="/tabdivapplications">TabDivApplications</Link>
        </li>
        <li>
          <Link to="/tabdivsuggestedtutors">TabDivSuggestedTutors</Link>
        </li>
        <li>
          <Link to="/tabdivupcominglessons">TabDivUpcomingLessons</Link>
        </li>
        <li>
          <Link to="/tabdivinterviews">TabDivInterviews</Link>
        </li>
        <li>
          <Link to="/tabdivcodeofconduct">TabDivCodeofConduct</Link>
        </li>
        <li>
          <Link to="/tabdivactivetutors">TabDivActiveTutors</Link>
        </li>
        <li>
          <Link to="/tabdivinactivetutors">TabDivInactiveTutors</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/tutoronboarding">TutorOnboarding</Link>
        </li>
        <li>
          <Link to="/tutordashboard">TutorDashboard</Link>
        </li>
        <li>
          <Link to="/profilesettingspage">ProfileSettingsPage</Link>
        </li>
        <li>
          <Link to="/tutorcodeofconduct">TutorCodeofConduct</Link>
        </li>
        <li>
          <Link to="/tutormybadges">TutorMyBadges</Link>
        </li>
        <li>
          <Link to="/profilesettingssubmenu">ProfileSettingsSubmenu</Link>
        </li>
        <li>
          <Link to="/historysettingssubmenu">HistorySettingsSubmenu</Link>
        </li>
        <li>
          <Link to="/tutoringsettingssubmenu">TutoringSettingsSubmenu</Link>
        </li>
        <li>
          <Link to="/studentlessonrequest">StudentLessonRequest</Link>
        </li>
        <li>
          <Link to="/findatutorpage">FindATutorPage</Link>
        </li>
        <li>
          <Link to="/tutorprofilepage">TutorProfilePage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
